'use strict';const e=document.getElementById("amount"),k=document.getElementById("pps_shop_items"),l=document.getElementById("shop_items"),m=document.getElementById("tap_power"),p=document.getElementById("pps"),q=document.getElementById("upgrades_count"),u=document.getElementById("change_keys"),v=document.getElementById("keys"),w=document.getElementById("main"),x=document.getElementById("bpm");y("All elements are not null",!!e&&!!k&&!!l&&!!m&&!!q&&!!u&&!!v&&!!x&&!!w);const z=Math.floor(40-40/11);
function y(a,b){if(!b)throw Error("Assertion failed: "+a);}function A(a,b){var c=B.i.u;return`Tap ${0>=c?"?":a.toUpperCase()}/${1>=c?"?":b.toUpperCase()} to gain pp.`}function C(a,b){return a.toFixed(b).replace(/\B(?=(\d{3})+(?!\d))/g,",")}
function D(a,b,c,d){const g=document.createElement("li"),f=document.createElement("button"),h=document.createElement("div"),n=document.createElement("div"),r=document.createElement("p"),t=document.createElement("p"),M=document.createTextNode(`${a.name}, ${a.j}${"pp"}`);b=document.createTextNode(b);const N=document.createTextNode(a.o);f.onclick=d;a=c+a.id;g.setAttribute("id","list_"+a);f.setAttribute("id","button_"+a);t.setAttribute("id","p_stat_"+a);r.setAttribute("id","p_"+a);n.setAttribute("id",
"desc_div_"+a);h.setAttribute("id","div_"+a);f.appendChild(M);t.appendChild(b);r.appendChild(N);n.appendChild(r);n.appendChild(t);"pps_item"==c&&(c=document.createElement("p"),c.setAttribute("id","p_producing_"+a),n.appendChild(c));h.appendChild(f);h.appendChild(n);g.appendChild(h);return g}
function E(a){const b=Array(a.g.length).fill(1);for(const d in a.l){var c=parseInt(d,10);if(!1!==a.i[c]&&(c=a.l[c],"multiplier"===c.action.type))for(const g in c.action.A)b[c.action.A[g]]*=c.action.value}return b}function F(a){const b=E(a);y("multipliers is valid length",b.length===a.g.length);return a.h.map((c,d)=>c*a.g[d].s*b[d]).reduce((c,d)=>c+d)}
class G{constructor(){this.g=[{id:0,name:"Keyboard button",o:"A button on an old keyboard.",j:80,s:.4},{id:1,name:"Trackball",o:"A pointing device.",j:440,s:1.6,m:[{type:"has_pps_upgrade",value:0}]},{id:2,name:"Drill",o:"Drill, usually fitted with a driving tool attachment,                    now fitted with a keyboard.",j:1960,s:4,m:[{type:"has_pps_upgrade",value:1,amount:2}]},{id:3,name:"Vaxei",o:"The following readme will serve to document all of Vaxei's skins.",j:9420,s:18,m:[{type:"has_pps_upgrade",
value:2,amount:3}]},{id:4,name:"Cookiezi",o:"Shigetora, better known online as chocomint and formerly as Cookiezi,                    is a famous South Korean osu!standard player.",j:74500,s:55,m:[{type:"has_pps_upgrade",value:3,amount:5}]}];this.l=[{id:0,name:"Spicy ramen",o:"You start to sweat.",stat:"+0.6 pp/tap",j:520,action:{type:"tap_power",value:.6}},{id:1,name:"Bateron switch",o:"You order some switches.",stat:"Keyboard buttons are twice more effective.",j:1340,action:{type:"multiplier",A:[0],
value:2},m:[{type:"has_pps_upgrade",value:0,amount:5}]},{id:2,name:"Mousepad",o:"Finally, less mouse drift.",stat:"+1.2 pp/tap",j:1800,action:{type:"tap_power",value:1.2},m:[{type:"has_upgrade",value:0}]},{id:3,name:"Vacom toilet",o:"10 Reasons Why You Might Want a High-Tech Super Toilet.",stat:"+3.2 pp/tap",j:4600,action:{type:"tap_power",value:3.2},m:[{type:"has_upgrade",value:2}]},{id:4,name:"Power outlet",o:"The consequences of industrial revolution.",stat:"Trackball and drill become twice as effective.",
j:10640,action:{type:"multiplier",A:[1,2],value:2},m:[{type:"has_pps_upgrade",value:1,amount:4},{type:"has_pps_upgrade",value:2,amount:2}]},{id:5,name:"Sugar",o:"The generic name for sweet-tasting, soluble carbohydrates,                    many of which are used in food.",stat:"Vaxei becomes twice as effective.",j:18900,action:{type:"multiplier",A:[3],value:2},m:[{type:"has_upgrade",value:4,amount:4}]},{id:6,name:"Mooting",o:"You finally receive your Mooting keyboard.",stat:"Click power is doubled.",
j:23200,action:{type:"tap_power_multiplier",value:2},m:[{type:"has_upgrade",value:5}]},{id:7,name:"Cookiezi comeback",o:"Chocomint's Made of Fire HDDT 98.54 full combo.                    Without a doubt, one of the most impressive plays ever set in osu! history,                    but one that takes some experience to appreciate fully.",stat:"Cookiezi becomes twice as effective.",j:69420,action:{type:"multiplier",A:[4],value:2},m:[{type:"has_upgrade",value:6,amount:3}]}];this.h=Array(this.g.length).fill(0);
this.i=Array(this.l.length).fill(!1)}}function H(a){var b=I;return function(){if(b.l<a.j)alert('Not enough pp to buy "'+a.name+'" :(');else{b.l-=a.j;var c=b.g;c.h[a.id]+=1;c.g[a.id].j=Math.floor(1.15*c.g[a.id].j);J(b);K(b);b.B=F(b.g)}}}
function L(a){var b=I;return function(){if(b.l<a.j)alert('Not enough pp to buy "'+a.name+'" :(');else{b.l-=a.j;var c=b.g;document.getElementById("button_item"+a.id).disabled=!0;c.i[a.id]=!0;J(b);K(b);c=b.g;let g=1,f=1;for(const h in c.i){var d=parseInt(h,10);if(!1!==c.i[d])switch(d=c.l[d],d?.action.type){case "tap_power":g+=d.action.value;break;case "tap_power_multiplier":f*=d.action.value}}b.G=g*f;b.B=F(b.g)}}}
function O(a,b){for(const c in b.m){const d=b.m[parseInt(c,10)];switch(d.type){case "has_pps":if(a.B<d.value)return!1;break;case "has_pps_upgrade":y("has_pps_upgrade value is not out of range",d.value<a.g.h.length);if(a.g.h[d.value]<(d.amount||1))return!1;break;case "has_current_pp":if(a.l<d.value)return!1;break;case "has_upgrade":y("has_upgrade value is not out of range",d.value<a.g.i.length);if(!a.g.i[d.value])return!1;break;case "total_pp":if(a.total<d.value)return!1}}return!0}
function J(a){for(const c in a.g.i){var b=parseInt(c,10);const d=a.g.l[b];a.g.i[b]&&(document.getElementById("button_item"+d.id).disabled=!0);b=document.getElementById("list_item"+d.id);d.m&&b.hidden?O(a,d)&&(b.hidden=!1):b.hidden=!1}}
function K(a){const b=E(a.g);for(const g in a.g.h){const f=a.g.g[parseInt(g,10)];var c=document.getElementById("button_pps_item"+f.id);const h=document.getElementById("p_stat_pps_item"+f.id);var d=a.g.h[f.id];c.textContent=`${f.name}, ${C(f.j,0)}${"pp"}`;h.textContent=`+${C(f.s*b[f.id],1)} ${"pp"}/s`;0<d&&(c=document.getElementById("p_producing_pps_item"+f.id),d=`You have ${d}, producing ${C(f.s*d*b[f.id],1)} ${"pp"}/s`,c.textContent=d);d=document.getElementById("list_pps_item"+f.id);f.m&&d.hidden?
O(a,f)&&(d.hidden=!1):d.hidden=!1}}function P(a){var b=B;a.D||(a.D=!0,b.h.v+=1,Q(b,b.G),b.h.F=!0,clearInterval(b.h.I),b.h.I=setTimeout(()=>{b.h.F=!1},2E3))}function Q(a,b){a.total+=b;a.l+=b}function R(a){const b=a.h.v*z/a.h.C;x.textContent=0<b?Math.floor(60*b/4)+" BPM":":3c";e.textContent=C(Math.floor(a.l),0)+"pp";p.textContent="pp/s: "+C(a.B+b,1);m.textContent="pp/tap: "+a.G;q.textContent="Items bought: "+a.g.h.reduce((c,d)=>c+d,0)}
class S{constructor(){this.H=0;this.h={I:0,F:!1,v:0,C:40};this.total=this.l=0;this.G=1;this.B=0;this.g=new G;this.i={keys:[{key:"z",D:!1},{key:"x",D:!1}],u:-1};y("settings.keys is of KEY_COUNT size",2===this.i.keys.length)}}const B=new S;var I=B;for(const a in I.g.g){const b=I.g.g[parseInt(a,10)],c=D(b,`+${b.s} ${"pp"}/s`,"pps_item",H(b));b.m&&(c.hidden=!0);k.appendChild(c)}for(const a in I.g.l){const b=I.g.l[parseInt(a,10)],c=D(b,b.stat,"item",L(b));b.m&&(c.hidden=!0);l.appendChild(c)}
setInterval(()=>{var a=B;Q(a,a.B/40);a.h.F?a.h.C+=1:40!=a.h.C?(a.h.v=Math.floor(a.h.v/a.h.C*z),a.h.C=40):0<a.h.v&&--a.h.v;R(a)},25);document.addEventListener("keydown",a=>{const b=B.i.keys[0],c=B.i.keys[1];if(0<=B.i.u)B.i.keys[B.i.u].key=a.key,B.i.u+=1,v.textContent=A(b.key,c.key),2<=B.i.u&&(B.i.u=-1,u.textContent="Change keys...");else switch(a.key.toLowerCase()){case b.key:P(b);break;case c.key:P(c)}});
document.addEventListener("keyup",a=>{const b=B.i.keys[0],c=B.i.keys[1];switch(a.key.toLowerCase()){case b.key:b.D=!1;break;case c.key:c.D=!1}});u.onclick=()=>{const a=B.i.keys[0],b=B.i.keys[1];B.i.u=0;v.textContent=A(a.key,b.key);u.textContent="Press a new key..."};window.onfocus=()=>{const a=(new Date).getTime()-B.H;1E3<a&&Q(B,a/1E3*B.B)};window.onblur=()=>{B.H=(new Date).getTime()};
