'use strict';const e=document.getElementById("amount"),l=document.getElementById("cps_shop_items"),m=document.getElementById("shop_items"),n=document.getElementById("tap_power"),p=document.getElementById("cps"),q=document.getElementById("upgrades_count"),r=document.getElementById("change_keys"),v=document.getElementById("keys"),w=document.getElementById("main"),x=document.getElementById("bpm");y("All elements are not null",!!e&&!!l&&!!m&&!!n&&!!l&&!!q&&!!r&&!!v&&!!x&&!!w);
const z=Math.floor(40-40/11);function y(a,b){if(!b)throw Error("Assertion failed: "+a);}function A(a,b){var c=B.i.s;return`Tap ${0>=c?"?":a.toUpperCase()}/${1>=c?"?":b.toUpperCase()} to gain pp.`}function C(a,b){return a.toFixed(b).replace(/\B(?=(\d{3})+(?!\d))/g,",")}
function D(a,b,c,d){const k=document.createElement("li"),g=document.createElement("button"),f=document.createElement("div"),h=document.createElement("div"),t=document.createElement("p"),u=document.createElement("p"),K=document.createTextNode(`${a.name}, ${a.h}${"pp"}`);b=document.createTextNode(b);const L=document.createTextNode(a.j);g.onclick=d;a=c+a.id;k.setAttribute("id","list_"+a);g.setAttribute("id","button_"+a);u.setAttribute("id","p_stat_"+a);t.setAttribute("id","p_"+a);h.setAttribute("id",
"desc_div_"+a);f.setAttribute("id","div_"+a);g.appendChild(K);u.appendChild(b);t.appendChild(L);h.appendChild(t);h.appendChild(u);"cps_item"==c&&(c=document.createElement("p"),c.setAttribute("id","p_producing_"+a),h.appendChild(c));f.appendChild(g);f.appendChild(h);k.appendChild(f);return k}
function E(a){const b=Array(a.m.length).fill(1);for(const d in a.v){var c=parseInt(d,10);if(0!==a.g[c]&&(c=a.v[c],"multiplier"===c?.action.type))for(const k in c.action.D){const g=c.action.D[k];b[g]=b[g]*a.g[g]*c.action.value}}return b}function F(a){const b=E(a);y("multipliers is valid length",b.length===a.m.length);return a.u.map((c,d)=>c*a.m[d].o*b[d]).reduce((c,d)=>c+d)}
function G(a){for(const b in a.g){const c=parseInt(b,10),d=a.v[c];0<a.g[c]&&(document.getElementById("button_item"+d.id).disabled=!0);0<a.g[c-1]&&(document.getElementById("list_item"+d.id).hidden=!1)}}
function H(a){const b=E(a);for(const k in a.u){const g=parseInt(k,10),f=a.m[g];var c=document.getElementById("button_cps_item"+f.id);const h=document.getElementById("p_stat_cps_item"+f.id);var d=a.u[f.id];c.textContent=`${f.name}, ${C(f.h,0)}${"pp"}`;h.textContent=`+${f.o*b[f.id]} ${"pp"}/s`;0<d&&(c=document.getElementById("p_producing_cps_item"+f.id),d=`You have ${d}, producing ${C(f.o*d*b[f.id],1)} ${"pp"}/s`,c.textContent=d);0<a.u[g-1]&&(document.getElementById("list_cps_item"+f.id).hidden=!1)}}
class I{constructor(){this.m=[{id:0,name:"Keyboard macro",j:"A macro on an old keyboard.",h:80,o:.4},{id:1,name:"Logitech",j:"Item description =D",h:440,o:1},{id:2,name:"A drill",j:"Drill, usually fitted with a driving tool attachment, now fitted with a keyboard.",h:1960,o:4},{id:3,name:"Vaxei",j:"Item description =D",h:9420,o:10},{id:4,name:"Cookiezi",j:"Item description =D",h:54500,o:50}];this.v=[{id:0,name:"Buldak",j:"You start to sweat.",stat:"+0.6 pp/tap",h:520,action:{type:"tap_power",value:.6}},
{id:1,name:"Gateron switch",j:"You order some switches.",stat:"Keyboard button is twice more effective.",h:1340,action:{type:"multiplier",D:[0],value:2}},{id:2,name:"Mousepad",j:"Finally, less mouse drift.",stat:"+1.2 pp/tap",h:1800,action:{type:"tap_power",value:1.2}},{id:3,name:"Wacom",j:"Item description =D",stat:"+3.2 pp/tap",h:4600,action:{type:"tap_power",value:3.2}},{id:4,name:"Power outlet",j:"The consequences of industrial revolution.",stat:"Keyboard buttons and drills become twice as effective.",
h:10640,action:{type:"multiplier",D:[1,2],value:2}},{id:5,name:"Sugar",j:"Item description =D",stat:"Vaxei becomes twice as effective.",h:18900,action:{type:"multiplier",D:[3],value:2}},{id:6,name:"Wooting",j:"You finally receive your Wooting.",stat:"Click power is doubled.",h:23200,action:{type:"tap_power_multiplier",value:2}},{id:7,name:"Cookiezi comeback",j:"Chocomint's Made of Fire HDDT 98.54 full combo. Without a doubt, one of the most impressive plays ever set in osu! history, but one that takes some experience to appreciate fully.",
stat:"Cookiezi becomes twice as effective.",h:69420,action:{type:"multiplier",D:[4],value:2}}];this.u=Array(this.m.length).fill(0);this.g=Array(this.v.length).fill(0)}G(a){this.g[a.id]+=1;document.getElementById("button_item"+a.id).disabled=!0;G(this);H(this)}H(a){this.u[a.id]+=1;this.m[a.id].h=Math.floor(1.15*this.m[a.id].h);H(this)}}function J(a){var b=B;a.C||(a.C=!0,b.g.A+=1,b.amount+=b.J,b.g.I=!0,clearInterval(b.g.L),b.g.L=setTimeout(()=>{b.g.I=!1},1E3))}
function M(a){const b=a.g.A*z/a.g.B;x.textContent=Math.floor(60*b/4)+" BPM";e.textContent=C(Math.floor(a.amount),0)+"pp";p.textContent="pp/s: "+C(a.F+b,1);n.textContent="pp/tap: "+a.J;q.textContent="Items bought: "+a.l.u.reduce((c,d)=>c+d,0)}
class N{constructor(){var a=O;this.K=0;this.g={L:0,I:!1,A:0,B:40};this.amount=0;this.J=1;this.F=0;this.l=a;this.i={keys:[{key:"z",C:!1},{key:"x",C:!1}],s:-1};y("settings.keys is of KEY_COUNT size",2===this.i.keys.length)}H(a){const b=this;return function(){b.amount<a.h?alert('Not enough pp to buy "'+a.name+'" :('):(b.amount-=a.h,b.l.H(a),H(b.l),b.F=F(b.l))}}G(a){const b=this;return function(){if(b.amount<a.h)alert('Not enough pp to buy "'+a.name+'" :(');else{b.amount-=a.h;b.l.G(a);G(b.l);var c=b.l;
let d=1,k=1;for(const g in c.g){const f=parseInt(g,10);if(0===c.g[f])continue;const h=c.v[f];switch(h?.action.type){case "tap_power":d+=h.action.value*c.g[f];break;case "tap_power_multiplier":k*=h.action.value*c.g[f]}}b.J=d*k;b.F=F(b.l)}}}}const O=new I,B=new N;var P=B;for(const a in P.l.m){const b=parseInt(a,10),c=P.l.m[b],d=D(c,`+${c.o} ${"pp"}/s`,"cps_item",P.H(c));0<b&&(d.hidden=!0);l.appendChild(d)}
for(const a in P.l.v){const b=parseInt(a,10),c=P.l.v[b],d=D(c,c.stat,"item",P.G(c));0<b&&(d.hidden=!0);m.appendChild(d)}setInterval(()=>{var a=B;a.amount+=a.F/40;a.g.I?a.g.B+=1:40!=a.g.B?(a.g.A=Math.floor(a.g.A/a.g.B*z),a.g.B=40):0<a.g.A&&--a.g.A;M(a)},25);
document.addEventListener("keydown",a=>{const b=B.i.keys[0],c=B.i.keys[1];if(0<=B.i.s)B.i.keys[B.i.s].key=a.key,B.i.s+=1,v.textContent=A(b.key,c.key),2<=B.i.s&&(B.i.s=-1,r.textContent="Change keys...");else switch(a.key.toLowerCase()){case b.key:J(b);break;case c.key:J(c)}});document.addEventListener("keyup",a=>{const b=B.i.keys[0],c=B.i.keys[1];switch(a.key.toLowerCase()){case b.key:b.C=!1;break;case c.key:c.C=!1}});
r.onclick=()=>{const a=B.i.keys[0],b=B.i.keys[1];B.i.s=0;v.textContent=A(a.key,b.key);r.textContent="Press a new key..."};window.onfocus=()=>{const a=(new Date).getTime()-B.K;1E3<a&&(B.amount+=a/1E3*B.F)};window.onblur=()=>{B.K=(new Date).getTime()};
