'use strict';const e=document.getElementById("amount"),l=document.getElementById("cps_shop_items"),m=document.getElementById("shop_items"),n=document.getElementById("tap_power"),p=document.getElementById("cps"),q=document.getElementById("upgrades_count"),r=document.getElementById("change_keys"),v=document.getElementById("keys"),w=document.getElementById("main"),x=document.getElementById("bpm");y("All elements are not null",!!e&&!!l&&!!m&&!!n&&!!l&&!!q&&!!r&&!!v&&!!x&&!!w);
const z=Math.floor(40-40/11);function y(a,b){if(!b)throw Error("Assertion failed: "+a);}function A(a,b){var c=B.j.A;return`Tap ${0>=c?"?":a.toUpperCase()}/${1>=c?"?":b.toUpperCase()} to gain pp.`}function C(a,b){return a.toFixed(b).replace(/\B(?=(\d{3})+(?!\d))/g,",")}
function D(a,b,c,d){const g=document.createElement("li"),f=document.createElement("button"),h=document.createElement("div"),k=document.createElement("div"),t=document.createElement("p"),u=document.createElement("p"),M=document.createTextNode(`${a.name}, ${a.h}${"pp"}`);b=document.createTextNode(b);const N=document.createTextNode(a.m);f.onclick=d;a=c+a.id;g.setAttribute("id","list_"+a);f.setAttribute("id","button_"+a);u.setAttribute("id","p_stat_"+a);t.setAttribute("id","p_"+a);k.setAttribute("id",
"desc_div_"+a);h.setAttribute("id","div_"+a);f.appendChild(M);u.appendChild(b);t.appendChild(N);k.appendChild(t);k.appendChild(u);"cps_item"==c&&(c=document.createElement("p"),c.setAttribute("id","p_producing_"+a),k.appendChild(c));h.appendChild(f);h.appendChild(k);g.appendChild(h);return g}
function E(a){const b=Array(a.s.length).fill(1);for(const d in a.B){var c=parseInt(d,10);if(0!==a.o[c]&&(c=a.B[c],"multiplier"===c.action.type))for(const g in c.action.D)b[c.action.D[g]]=b[c.action.D[g]]*a.o[c.id]*c.action.value}return b}function F(a){const b=E(a);y("multipliers is valid length",b.length===a.s.length);return a.u.map((c,d)=>c*a.s[d].v*b[d]).reduce((c,d)=>c+d)}
class G{constructor(){this.s=[{id:0,name:"Keyboard button",m:"A button on an old keyboard.",h:80,v:.4},{id:1,name:"Logitech",m:"Item description =D",h:440,v:1,l:[{type:"has_cps_upgrade",value:0}]},{id:2,name:"A drill",m:"Drill, usually fitted with a driving tool attachment, now fitted with a keyboard.",h:1960,v:4,l:[{type:"has_cps_upgrade",value:1,amount:2}]},{id:3,name:"Vaxei",m:"Item description =D",h:9420,v:10,l:[{type:"has_cps_upgrade",value:2,amount:3}]},{id:4,name:"Cookiezi",m:"Item description =D",
h:74500,v:55,l:[{type:"has_cps_upgrade",value:3,amount:5}]}];this.B=[{id:0,name:"Spicy ramen",m:"You start to sweat.",stat:"+0.6 pp/tap",h:520,action:{type:"tap_power",value:.6}},{id:1,name:"Bateron switch",m:"You order some switches.",stat:"Keyboard buttons are thrice more effective.",h:1340,action:{type:"multiplier",D:[0],value:3},l:[{type:"has_cps_upgrade",value:0,amount:5}]},{id:2,name:"Mousepad",m:"Finally, less mouse drift.",stat:"+1.2 pp/tap",h:1800,action:{type:"tap_power",value:1.2},l:[{type:"has_upgrade",
value:0},{type:"has_pps",value:10}]},{id:3,name:"Vacom toilet",m:"10 Reasons Why You Might Want a High-Tech Super Toilet",stat:"+3.2 pp/tap",h:4600,action:{type:"tap_power",value:3.2},l:[{type:"has_upgrade",value:2}]},{id:4,name:"Power outlet",m:"The consequences of industrial revolution.",stat:"Logitech and drill become twice as effective.",h:10640,action:{type:"multiplier",D:[1,2],value:2},l:[{type:"has_cps_upgrade",value:1,amount:4},{type:"has_cps_upgrade",value:2,amount:2}]},{id:5,name:"Sugar",
m:"The generic name for sweet-tasting, soluble carbohydrates, many of which are used in food.",stat:"Vaxei becomes twice as effective.",h:18900,action:{type:"multiplier",D:[3],value:2},l:[{type:"has_upgrade",value:4,amount:4}]},{id:6,name:"Mooting",m:"You finally receive your Mooting keyboard.",stat:"Click power is doubled.",h:23200,action:{type:"tap_power_multiplier",value:2},l:[{type:"has_upgrade",value:5}]},{id:7,name:"Cookiezi comeback",m:"Chocomint's Made of Fire HDDT 98.54 full combo. Without a doubt, one of the most impressive plays ever set in osu! history, but one that takes some experience to appreciate fully.",
stat:"Cookiezi becomes twice as effective.",h:69420,action:{type:"multiplier",D:[4],value:2},l:[{type:"has_upgrade",value:6,amount:3}]}];this.u=Array(this.s.length).fill(0);this.o=Array(this.B.length).fill(0)}I(a){this.o[a.id]+=1;document.getElementById("button_item"+a.id).disabled=!0}J(a){this.u[a.id]+=1;this.s[a.id].h=Math.floor(1.15*this.s[a.id].h)}}
function H(a,b){for(const c in b.l){const d=b.l[parseInt(c,10)];switch(d.type){case "has_cps":if(a.F<d.value)return!1;break;case "has_cps_upgrade":y("has_cps_upgrade value is not out of range",d.value<a.g.u.length);if(a.g.u[d.value]<(d.amount||1))return!1;break;case "has_current_pp":if(a.amount<d.value)return!1;break;case "has_upgrade":y("has_upgrade value is not out of range",d.value<a.g.o.length);if(1>a.g.o[d.value])return!1;break;case "total_pp":if(a.total<d.value)return!1}}return!0}
function I(a){for(const c in a.g.o){var b=parseInt(c,10);const d=a.g.B[b];0<a.g.o[b]&&(document.getElementById("button_item"+d.id).disabled=!0);b=document.getElementById("list_item"+d.id);d.l&&!0===b.hidden?H(a,d)&&(b.hidden=!1):b.hidden=!1}}
function J(a){const b=E(a.g);for(const g in a.g.u){const f=a.g.s[parseInt(g,10)];var c=document.getElementById("button_cps_item"+f.id);const h=document.getElementById("p_stat_cps_item"+f.id);var d=a.g.u[f.id];c.textContent=`${f.name}, ${C(f.h,0)}${"pp"}`;h.textContent=`+${C(f.v*b[f.id],1)} ${"pp"}/s`;0<d&&(c=document.getElementById("p_producing_cps_item"+f.id),d=`You have ${d}, producing ${C(f.v*d*b[f.id],1)} ${"pp"}/s`,c.textContent=d);d=document.getElementById("list_cps_item"+f.id);f.l&&!0===d.hidden?
H(a,f)&&(d.hidden=!1):d.hidden=!1}}function K(a){var b=B;a.H||(a.H=!0,b.i.C+=1,L(b,b.L),b.i.K=!0,clearInterval(b.i.N),b.i.N=setTimeout(()=>{b.i.K=!1},1E3))}function L(a,b){a.total+=b;a.amount+=b}function O(a){const b=a.i.C*z/a.i.G;x.textContent=0<b?Math.floor(60*b/4)+" BPM":":3c";e.textContent=C(Math.floor(a.amount),0)+"pp";p.textContent="pp/s: "+C(a.F+b,1);n.textContent="pp/tap: "+a.L;q.textContent="Items bought: "+a.g.u.reduce((c,d)=>c+d,0)}
class P{constructor(){var a=Q;this.M=0;this.i={N:0,K:!1,C:0,G:40};this.total=this.amount=0;this.L=1;this.F=0;this.g=a;this.j={keys:[{key:"z",H:!1},{key:"x",H:!1}],A:-1};y("settings.keys is of KEY_COUNT size",2===this.j.keys.length)}J(a){const b=this;return function(){b.amount<a.h?alert('Not enough pp to buy "'+a.name+'" :('):(b.amount-=a.h,b.g.J(a),I(b),J(b),b.F=F(b.g))}}I(a){const b=this;return function(){if(b.amount<a.h)alert('Not enough pp to buy "'+a.name+'" :(');else{b.amount-=a.h;b.g.I(a);I(b);
J(b);var c=b.g;let d=1,g=1;for(const f in c.o){const h=parseInt(f,10);if(0===c.o[h])continue;const k=c.B[h];switch(k?.action.type){case "tap_power":d+=k.action.value*c.o[h];break;case "tap_power_multiplier":g*=k.action.value*c.o[h]}}b.L=d*g;b.F=F(b.g)}}}}const Q=new G,B=new P;var R=B;for(const a in R.g.s){const b=R.g.s[parseInt(a,10)],c=D(b,`+${b.v} ${"pp"}/s`,"cps_item",R.J(b));b.l&&(c.hidden=!0);l.appendChild(c)}
for(const a in R.g.B){const b=R.g.B[parseInt(a,10)],c=D(b,b.stat,"item",R.I(b));b.l&&(c.hidden=!0);m.appendChild(c)}setInterval(()=>{var a=B;L(a,a.F/40);a.i.K?a.i.G+=1:40!=a.i.G?(a.i.C=Math.floor(a.i.C/a.i.G*z),a.i.G=40):0<a.i.C&&--a.i.C;O(a)},25);
document.addEventListener("keydown",a=>{const b=B.j.keys[0],c=B.j.keys[1];if(0<=B.j.A)B.j.keys[B.j.A].key=a.key,B.j.A+=1,v.textContent=A(b.key,c.key),2<=B.j.A&&(B.j.A=-1,r.textContent="Change keys...");else switch(a.key.toLowerCase()){case b.key:K(b);break;case c.key:K(c)}});document.addEventListener("keyup",a=>{const b=B.j.keys[0],c=B.j.keys[1];switch(a.key.toLowerCase()){case b.key:b.H=!1;break;case c.key:c.H=!1}});
r.onclick=()=>{const a=B.j.keys[0],b=B.j.keys[1];B.j.A=0;v.textContent=A(a.key,b.key);r.textContent="Press a new key..."};window.onfocus=()=>{const a=(new Date).getTime()-B.M;1E3<a&&L(B,a/1E3*B.F)};window.onblur=()=>{B.M=(new Date).getTime()};
