'use strict';const e=document.getElementById("amount"),h=document.getElementById("pps_shop_items"),l=document.getElementById("general_shop_items"),m=document.getElementById("tap_power"),n=document.getElementById("pps"),p=document.getElementById("upgrade_count"),r=document.getElementById("change_keys"),u=document.getElementById("keys"),x=document.getElementById("bpm");y("All elements are not null",!!e&&!!h&&!!l&&!!m&&!!p&&!!r&&!!u&&!!x);function y(a,b){if(!b)throw Error("Assertion failed: "+a);}
function z(a,b){var c=A.i.u;return`Tap ${0>=c?"?":a.toUpperCase()}/${1>=c?"?":b.toUpperCase()} to gain pp.`}function B(a,b){return a.toFixed(b).replace(/\B(?=(\d{3})+(?!\d))/g,",")}
function C(a,b,c,d){const g=document.createElement("li"),f=document.createElement("button"),k=document.createElement("div"),G=document.createElement("div"),v=document.createElement("div"),q=document.createElement("div"),t=document.createElement("p"),w=document.createElement("p"),O=document.createTextNode(a.name),P=document.createTextNode(a.j+"pp");b=document.createTextNode(b);const Q=document.createTextNode(a.o);f.onclick=d;a=c+a.id;g.setAttribute("id","list_"+a);f.setAttribute("id","button_"+a);
w.setAttribute("id","p_stat_"+a);t.setAttribute("id","p_"+a);q.setAttribute("id","desc_div_"+a);v.setAttribute("id","cost_div_"+a);k.setAttribute("id","div_"+a);t.setAttribute("class","description");v.appendChild(P);G.appendChild(O);f.appendChild(G);f.appendChild(v);w.appendChild(b);t.appendChild(Q);q.appendChild(w);q.appendChild(t);"pps_item"==c&&(c=document.createElement("p"),c.setAttribute("id","p_producing_"+a),q.appendChild(c));k.appendChild(f);k.appendChild(q);g.appendChild(k);return g}
let D=0,E=0;function F(a){const b=Array(a.g.length).fill(1);for(const d in a.l){var c=parseInt(d,10);if(!1!==a.i[c]&&(c=a.l[c],"multiplier"===c.action.type))for(const g in c.action.v)b[c.action.v[g]]*=c.action.value}return b}function H(a){const b=F(a);y("multipliers is valid length",b.length===a.g.length);return a.h.map((c,d)=>c*a.g[d].s*b[d]).reduce((c,d)=>c+d)}
class I{constructor(){this.g=[{id:E++,name:"Keyboard button",o:"A button on an old keyboard.",j:80,s:.4},{id:E++,name:"Trackball",o:"A pointing device.",j:540,s:2.6,m:[{type:"has_pps_upgrade",value:0,amount:2}]},{id:E++,name:"Drill",o:"Drill, usually fitted with a driving tool attachment,                    now fitted with a keyboard.",j:3770,s:6,m:[{type:"has_pps_upgrade",value:1,amount:4}]},{id:E++,name:"Vaxei",o:"The following README will serve to document all of Vaxei's skins.",j:29E3,s:36,m:[{type:"has_pps_upgrade",
value:2,amount:4}]},{id:E++,name:"Cookiezi",o:"Shigetora, better known online as chocomint and formerly as Cookiezi,                    is a famous South Korean osu!standard player.",j:205E3,s:102,m:[{type:"has_pps_upgrade",value:3,amount:5}]}];this.l=[{id:D++,name:"Spicy ramen",o:"You start to sweat.",stat:"+0.6 pp/tap",j:520,action:{type:"tap_power",value:.6}},{id:D++,name:"Bateron switch",o:"You order some switches.",stat:"Keyboard buttons are twice more effective.",j:1340,action:{type:"multiplier",
v:[0],value:2},m:[{type:"has_pps_upgrade",value:0,amount:5}]},{id:D++,name:"Mousepad",o:"Finally, less mouse drift.",stat:"+1.2 pp/tap",j:1800,action:{type:"tap_power",value:1.2},m:[{type:"has_upgrade",value:0}]},{id:D++,name:"Vacom toilet",o:"10 Reasons Why You Might Want a High-Tech Super Toilet.",stat:"+3.2 pp/tap",j:5600,action:{type:"tap_power",value:3.2},m:[{type:"has_upgrade",value:2}]},{id:D++,name:"Ultra lube",o:"You lube you keyboard.",stat:"Keyboard buttons are twice more effective.",j:8040,
action:{type:"multiplier",v:[0],value:2},m:[{type:"has_pps_upgrade",value:0,amount:12}]},{id:D++,name:"Power outlet",o:"The consequences of industrial revolution.",stat:"Trackball and drill become twice as effective.",j:15640,action:{type:"multiplier",v:[1,2],value:2},m:[{type:"has_pps_upgrade",value:1,amount:4},{type:"has_pps_upgrade",value:2,amount:2}]},{id:D++,name:"Mooting",o:"You finally receive your Mooting keyboard.",stat:"Click power is doubled.",j:23200,action:{type:"tap_power_multiplier",
value:2},m:[{type:"has_upgrade",value:5}]},{id:D++,name:"Sugar",o:"The generic name for sweet-tasting, soluble carbohydrates,                    many of which are used in food.",stat:"Vaxei becomes twice as effective.",j:164900,action:{type:"multiplier",v:[3],value:2},m:[{type:"has_pps_upgrade",value:3,amount:4}]},{id:D++,name:"Cookiezi comeback",o:"Chocomint's Made of Fire HDDT 98.54 full combo.                    Without a doubt, one of the most impressive plays ever set in osu! history,                    but one that takes some experience to appreciate fully.",
stat:"Cookiezi becomes twice as effective.",j:569E3,action:{type:"multiplier",v:[4],value:2},m:[{type:"has_pps_upgrade",value:4,amount:3}]}];this.h=Array(this.g.length).fill(0);this.i=Array(this.l.length).fill(!1)}}function J(a){var b=K;return function(){if(b.l<a.j)alert('Not enough pp to buy "'+a.name+'" :(');else{b.l-=a.j;var c=b.g;c.h[a.id]+=1;c.g[a.id].j=Math.floor(1.15*c.g[a.id].j);L(b);M(b);b.B=H(b.g)}}}
function N(a){var b=K;return function(){if(b.l<a.j)alert('Not enough pp to buy "'+a.name+'" :(');else{b.l-=a.j;var c=b.g;document.getElementById("button_item"+a.id).disabled=!0;c.i[a.id]=!0;L(b);M(b);c=b.g;let g=1,f=1;for(const k in c.i){var d=parseInt(k,10);if(!1!==c.i[d])switch(d=c.l[d],d?.action.type){case "tap_power":g+=d.action.value;break;case "tap_power_multiplier":f*=d.action.value}}b.G=g*f;b.B=H(b.g)}}}
function R(a,b){for(const c in b.m){const d=b.m[parseInt(c,10)];switch(d.type){case "has_pps":if(a.B<d.value)return!1;break;case "has_pps_upgrade":y("has_pps_upgrade value is not out of range",d.value<a.g.h.length);if(a.g.h[d.value]<(d.amount||1))return!1;break;case "has_current_pp":if(a.l<d.value)return!1;break;case "has_upgrade":y("has_upgrade value is not out of range",d.value<a.g.i.length);if(!a.g.i[d.value])return!1;break;case "total_pp":if(a.total<d.value)return!1}}return!0}
function L(a){for(const c in a.g.i){var b=parseInt(c,10);const d=a.g.l[b];a.g.i[b]&&(document.getElementById("button_item"+d.id).disabled=!0);b=document.getElementById("list_item"+d.id);d.m&&b.hidden?R(a,d)&&(b.hidden=!1):b.hidden=!1}}
function M(a){const b=F(a.g);for(const g in a.g.h){const f=a.g.g[parseInt(g,10)];var c=document.getElementById("cost_div_pps_item"+f.id);const k=document.getElementById("p_stat_pps_item"+f.id);var d=a.g.h[f.id];c.textContent=`${B(f.j,0)}${"pp"}`;k.textContent=`+${B(f.s*b[f.id],1)} ${"pp"}/s`;0<d&&(c=document.getElementById("p_producing_pps_item"+f.id),d=`You have ${d}, producing ${B(f.s*d*b[f.id],1)} ${"pp"}/s`,c.textContent=d);d=document.getElementById("list_pps_item"+f.id);f.m&&d.hidden?R(a,f)&&
(d.hidden=!1):d.hidden=!1}}function S(a){var b=A;a.D||(a.D=!0,b.h.A+=1,T(b,b.G),b.h.F=!0,clearInterval(b.h.I),b.h.I=setTimeout(()=>{b.h.F=!1},2E3))}function T(a,b){a.total+=b;a.l+=b}function U(a){const b=44*a.h.A/a.h.C;x.textContent=0<b?Math.floor(60*b/4)+" BPM":":3c";e.textContent=B(Math.floor(a.l),0)+"pp";n.textContent="pp/s: "+B(a.B,1);m.textContent="pp/tap: "+a.G;p.textContent="Items bought: "+a.g.h.reduce((c,d)=>c+d,0)}
class V{constructor(){this.H=0;this.h={I:0,F:!1,A:0,C:40};this.total=this.l=0;this.G=1;this.B=0;this.g=new I;this.i={keys:[{key:"z",D:!1},{key:"x",D:!1}],u:-1};y("settings.keys is of KEY_COUNT size",2===this.i.keys.length)}}const A=new V;var K=A;for(const a in K.g.g){const b=K.g.g[parseInt(a,10)],c=C(b,`+${b.s} ${"pp"}/s`,"pps_item",J(b));b.m&&(c.hidden=!0);h.appendChild(c)}for(const a in K.g.l){const b=K.g.l[parseInt(a,10)],c=C(b,b.stat,"item",N(b));b.m&&(c.hidden=!0);l.appendChild(c)}
setInterval(()=>{var a=A;T(a,a.B/40);a.h.F?a.h.C+=1:40!=a.h.C?(a.h.A=Math.floor(a.h.A/a.h.C*44),a.h.C=40):0<a.h.A&&--a.h.A;U(a)},25);document.addEventListener("keydown",a=>{const b=A.i.keys[0],c=A.i.keys[1];if(0<=A.i.u)A.i.keys[A.i.u].key=a.key,A.i.u+=1,u.textContent=z(b.key,c.key),2<=A.i.u&&(A.i.u=-1,r.disabled=!1,r.textContent="Change keys...");else switch(a.key.toLowerCase()){case b.key:S(b);break;case c.key:S(c)}});
document.addEventListener("keyup",a=>{const b=A.i.keys[0],c=A.i.keys[1];switch(a.key.toLowerCase()){case b.key:b.D=!1;break;case c.key:c.D=!1}});r.onclick=()=>{const a=A.i.keys[0],b=A.i.keys[1];A.i.u=0;r.disabled=!0;u.textContent=z(a.key,b.key);r.textContent="Press a new key..."};window.onfocus=()=>{const a=(new Date).getTime()-A.H;1E3<a&&T(A,a/1E3*A.B)};window.onblur=()=>{A.H=(new Date).getTime()};
