'use strict';const e=document.getElementById("amount"),g=document.getElementById("pps_shop_items"),l=document.getElementById("general_shop_items"),m=document.getElementById("tap_power"),n=document.getElementById("pps"),p=document.getElementById("upgrade_count"),t=document.getElementById("change_keys"),w=document.getElementById("keys"),x=document.getElementById("bpm");console.assert(!!e&&!!g&&!!l&&!!m&&!!p&&!!t&&!!w&&!!x,"All elements are not null");
function y(a,b){var c=z.j.v;return`Tap ${0>=c?"?":a.toUpperCase()}/${1>=c?"?":b.toUpperCase()} to gain pp.`}function A(a,b){return a.toFixed(b).replace(/\B(?=(\d{3})+(?!\d))/g,",")}
function B(a,b,c,d){const h=document.createElement("li"),f=document.createElement("button"),k=document.createElement("div"),F=document.createElement("div"),u=document.createElement("div"),q=document.createElement("div"),r=document.createElement("p"),v=document.createElement("p"),N=document.createTextNode(a.name),O=document.createTextNode(A(a.h,0)+"pp");b=document.createTextNode(b);const P=document.createTextNode(a.m);f.onclick=d;a=c+a.id;h.setAttribute("id","list_"+a);f.setAttribute("id","button_"+
a);v.setAttribute("id","p_stat_"+a);r.setAttribute("id","p_"+a);q.setAttribute("id","desc_div_"+a);u.setAttribute("id","cost_div_"+a);k.setAttribute("id","div_"+a);r.setAttribute("class","description");u.appendChild(O);F.appendChild(N);f.appendChild(F);f.appendChild(u);v.appendChild(b);r.appendChild(P);q.appendChild(v);q.appendChild(r);"pps_item"===c&&(c=document.createElement("p"),c.setAttribute("id","p_producing_"+a),q.appendChild(c));k.appendChild(f);k.appendChild(q);h.appendChild(k);return h}
function C(a){alert(`${"To be fair, you have to have a very high IQ to understand technical mapping. The SV changes are extremely subtle, and without a solid grasp of music theory most of the quality will go over a typical player's head. There's also Monstrata's triangular outlook, which is deftly woven into his mapping - his personal philosophy draws heavily from Pishifat literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the Depths of these patterns, to realize that they're not just high quality- they say something deep about MAPPING. As a consequence people who dislike technical maps truly ARE idiots- of course they wouldn't appreciate, for instance, the quality in Sotarks' existencial catchphrase \"this needs more overdone jumps,\" which itself is a Cryptic reference to Monstrata's map quaver. I'm smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as Natsu's genius unfolds itself on their computer screens. What fools... how I pity them. \ud83d\ude02 And yes by the way, I DO have a Monstrata slider butterfly tattoo. And no, you cannot see it. It's for the ladies' eyes only- And even they have to demonstrate that they're within 5 PP points of my own (preferably lower) beforehand."}\n\nYou completed the game in ${Math.floor(((new Date).getTime()-
a.J)/1E3/60)} minutes.\nThanks for playing.`)}let D=0,E=0;function G(a){const b=Array(a.g.length).fill(1);for(const d in a.o){var c=parseInt(d,10);if(!1!==a.j[c]&&(c=a.o[c],"multiplier"===c.action.type))for(const h in c.action.s)b[c.action.s[h]]*=c.action.value}return b}function H(a){const b=G(a);console.assert(b.length===a.g.length,"multipliers is valid length");return a.i.map((c,d)=>c*a.g[d].u*b[d]).reduce((c,d)=>c+d)}
class I{constructor(){this.g=[{id:E++,name:"Keyboard button",m:"A button on an old keyboard.",h:80,u:.4},{id:E++,name:"Trackball",m:"A pointing device.",h:540,u:2.6,l:[{type:"has_pps_upgrade",item:0,amount:4}]},{id:E++,name:"Drill",m:"Drill, usually fitted with a driving tool attachment,                    now fitted with a keyboard.",h:2770,u:8,l:[{type:"has_pps_upgrade",item:1,amount:6}]},{id:E++,name:"Vaxei",m:"The following README will serve to document all of Vaxei's skins.",h:19E3,u:42,l:[{type:"has_pps_upgrade",
item:2,amount:6}]},{id:E++,name:"Cookiezi",m:"Shigetora, better known online as chocomint and formerly as Cookiezi,                    is a famous South Korean osu!standard player.",h:85E3,u:164,l:[{type:"has_pps_upgrade",item:3,amount:6}]},{id:E++,name:"Aetrna",m:"Once, he fingered a girl. She died.",h:496E3,u:1100,l:[{type:"has_pps_upgrade",item:4,amount:6}]},{id:E++,name:"peppy",m:"The creator of the.",h:5496E3,u:12800,l:[{type:"has_pps_upgrade",item:5,amount:6}]}];this.o=[{id:D++,name:"Bateron switch",
m:"You order some switches.",stat:"Keyboard buttons are twice more effective.",h:340,action:{type:"multiplier",s:[0],value:2},l:[{type:"has_pps_upgrade",item:0,amount:5}]},{id:D++,name:"Spicy ramen",m:"You start to sweat.",stat:"+0.6 pp/tap",h:620,action:{type:"tap_power",value:.6}},{id:D++,name:"Mousepad",m:"Finally, less mouse drift.",stat:"+1.2 pp/tap",h:1800,action:{type:"tap_power",value:1.2},l:[{type:"has_upgrade",item:0}]},{id:D++,name:"Vacom toilet",m:"10 Reasons Why You Might Want a High-Tech Super Toilet.",
stat:"+3.2 pp/tap",h:5600,action:{type:"tap_power",value:3.2},l:[{type:"has_upgrade",item:2}]},{id:D++,name:"Ultra lube",m:"You waste several hours lubing your keyboard.",stat:"Keyboard buttons are twice more effective.",h:8040,action:{type:"multiplier",s:[0],value:2},l:[{type:"has_pps_upgrade",item:0,amount:12}]},{id:D++,name:"Power outlet",m:"The consequences of industrial revolution.",stat:"Trackballs and drills become twice as effective.",h:15640,action:{type:"multiplier",s:[1,2],value:2},l:[{type:"has_pps_upgrade",
item:1,amount:4},{type:"has_pps_upgrade",item:2,amount:2}]},{id:D++,name:"Mooting",m:"You finally receive your Mooting keyboard.",stat:"Click power is doubled.",h:23200,action:{type:"tap_power_multiplier",value:2},l:[{type:"has_upgrade",item:5}]},{id:D++,name:"Sugar",m:"The generic name for sweet-tasting, soluble carbohydrates,                    many of which are used in food.",stat:"Vaxei becomes twice as effective.",h:84900,action:{type:"multiplier",s:[3],value:2},l:[{type:"has_pps_upgrade",item:3,
amount:10}]},{id:D++,name:"PP rework",m:"I am justice, I am honor, I am hope and living water.",stat:"You gain +20% PP/s",h:282E3,action:{type:"multiplier",s:[0,1,2,3,4,5],value:1.2},l:[{type:"has_pps_upgrade",item:5,amount:2}]},{id:D++,name:"Cookiezi comeback",m:"Chocomint's Made of Fire HDDT 98.54 full combo.                    Without a doubt, one of the most impressive plays ever set in osu! history,                    but one that takes some experience to appreciate fully.",stat:"Cookiezi becomes twice as effective.",
h:379E3,action:{type:"multiplier",s:[4],value:2},l:[{type:"has_pps_upgrade",item:4,amount:3}]},{id:D++,name:"Rising fevers",m:"Ascencion to heaven.",stat:"Xeltol is twice more effective.",h:726E4,action:{type:"multiplier",s:[5],value:2},l:[{type:"has_pps_upgrade",item:5,amount:6}]},{id:D++,name:"osu! lazer",m:"2042",stat:"You gain 20% PP/s.",h:406E4,action:{type:"multiplier",s:[0,1,2,3,4,5],value:1.2},l:[{type:"has_upgrade",item:9},{type:"has_upgrade",item:10},{type:"has_pps_upgrade",item:5,amount:6}]},
{id:D++,name:"Private jet",m:"Make peppy's dreams come true.",stat:"Makes peppy work twice as fast.",h:29E6,action:{type:"multiplier",s:[6],value:2},l:[{type:"has_pps_upgrade",item:6,amount:4}]},{id:D++,name:"Rank #1",m:"Hopefully this game has given you some osu! of all time.",stat:"...",h:727E5,action:{type:"func",action:C},l:[{type:"has_upgrade",item:11},{type:"has_upgrade",item:12}]}];this.i=Array(this.g.length).fill(0);this.j=Array(this.o.length).fill(!1)}}
function J(a){var b=K;return function(){if(b.o<a.h)alert('Not enough pp to buy "'+a.name+'" :(');else{b.o-=a.h;var c=b.g;c.i[a.id]+=1;c.g[a.id].h=Math.floor(1.15*c.g[a.id].h);L(b);M(b);b.B=H(b.g)}}}
function Q(a){var b=K;return function(){if(b.o<a.h)alert('Not enough pp to buy "'+a.name+'" :(');else{b.o-=a.h;var c=b.g;document.getElementById("button_item"+a.id).disabled=!0;c.j[a.id]=!0;"func"===a.action.type&&a.action.action(b);L(b);M(b);c=b.g;let h=1,f=1;for(const k in c.j){var d=parseInt(k,10);if(!1!==c.j[d])switch(d=c.o[d],d?.action.type){case "tap_power":h+=d.action.value;break;case "tap_power_multiplier":f*=d.action.value}}b.G=h*f;b.B=H(b.g)}}}
function R(a,b){if(!b.l)return!0;for(const c in b.l){const d=b.l[parseInt(c,10)];switch(d.type){case "has_pps":if(a.B<d.value)return!1;break;case "has_pps_upgrade":console.assert(d.item<a.g.i.length,"has_pps_upgrade value is not out of range");if(a.g.i[d.item]<(d.amount||1))return!1;break;case "has_current_pp":if(a.o<d.value)return!1;break;case "has_upgrade":console.assert(d.item<a.g.j.length,"has_upgrade value is not out of range");if(!a.g.j[d.item])return!1;break;case "total_pp":if(a.total<d.value)return!1}}return!0}
function L(a){for(const c in a.g.j){var b=parseInt(c,10);const d=a.g.o[b];a.g.j[b]&&(document.getElementById("button_item"+d.id).disabled=!0);b=document.getElementById("list_item"+d.id);d.l&&b.hidden?R(a,d)&&(b.hidden=!1):b.hidden=!1}}
function M(a){const b=G(a.g);for(const h in a.g.i){const f=a.g.g[parseInt(h,10)];var c=document.getElementById("cost_div_pps_item"+f.id);const k=document.getElementById("p_stat_pps_item"+f.id);var d=a.g.i[f.id];c.textContent=`${A(f.h,0)}${"pp"}`;k.textContent=`+${A(f.u*b[f.id],1)} ${"pp"}/s`;0<d&&(c=document.getElementById("p_producing_pps_item"+f.id),d=`You have ${d}, producing ${A(f.u*d*b[f.id],1)} ${"pp"}/s`,c.textContent=d);d=document.getElementById("list_pps_item"+f.id);f.l&&d.hidden?R(a,f)&&
(d.hidden=!1):d.hidden=!1}}function S(a){var b=z;a.D||(a.D=!0,b.i.A+=1,T(b,b.G),b.i.F=!0,clearInterval(b.i.I),b.i.I=setTimeout(()=>{b.i.F=!1},2E3))}function T(a,b){a.total+=b;a.o+=b}function U(a){const b=44*a.i.A/a.i.C;x.textContent=0<b?Math.floor(60*b/4)+" BPM":":3c";e.textContent=A(Math.floor(a.o),0)+"pp";n.textContent="pp/s: "+A(a.B,1);m.textContent="pp/tap: "+a.G;p.textContent="Items bought: "+a.g.i.reduce((c,d)=>c+d,0)}
class V{constructor(){this.H=0;this.i={I:0,F:!1,A:0,C:40};this.total=this.o=0;this.G=1;this.B=0;this.J=(new Date).getTime();this.g=new I;this.j={keys:[{key:"z",D:!1},{key:"x",D:!1}],v:-1};console.assert(2===this.j.keys.length,"settings.keys is of KEY_COUNT size")}}const z=new V;var K=z;for(const a in K.g.g){const b=K.g.g[parseInt(a,10)],c=B(b,`+${b.u} ${"pp"}/s`,"pps_item",J(b));b.l&&(c.hidden=!0);g.appendChild(c)}
for(const a in K.g.o){const b=K.g.o[parseInt(a,10)],c=B(b,b.stat,"item",Q(b));b.l&&(c.hidden=!0);l.appendChild(c)}setInterval(()=>{var a=z;T(a,a.B/40);a.i.F?a.i.C+=1:40!=a.i.C?(a.i.A=Math.floor(a.i.A/a.i.C*44),a.i.C=40):0<a.i.A&&--a.i.A;U(a)},25);
document.addEventListener("keydown",a=>{const b=z.j.keys[0],c=z.j.keys[1];if(0<=z.j.v)z.j.keys[z.j.v].key=a.key,z.j.v+=1,w.textContent=y(b.key,c.key),2<=z.j.v&&(z.j.v=-1,t.disabled=!1,t.textContent="Change keys...");else switch(a.key.toLowerCase()){case b.key:S(b);break;case c.key:S(c)}});document.addEventListener("keyup",a=>{const b=z.j.keys[0],c=z.j.keys[1];switch(a.key.toLowerCase()){case b.key:b.D=!1;break;case c.key:c.D=!1}});
t.onclick=()=>{const a=z.j.keys[0],b=z.j.keys[1];z.j.v=0;t.disabled=!0;w.textContent=y(a.key,b.key);t.textContent="Press a new key..."};window.onfocus=()=>{const a=(new Date).getTime()-z.H;1E3<a&&T(z,a/1E3*z.B)};window.onblur=()=>{z.H=(new Date).getTime()};
